import { Listing } from '@/types'

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    user_id: null,
    type: 'vente',
    title: 'T3 lumineux centre-ville',
    location: 'Bayonne · Petit Bayonne',
    price: 245000,
    surface: 68,
    rooms: 3,
    description: 'Bel appartement T3 lumineux au cœur du Petit Bayonne. Parquet ancien, moulures, double vitrage. Proche commerces et transports.',
    source: 'seloger',
    external_url: 'https://seloger.com',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    user_id: null,
    type: 'location',
    title: 'T2 meublé standing',
    location: 'Anglet · Chambre d\'Amour',
    price: 890,
    surface: 45,
    rooms: 2,
    description: 'T2 meublé haut standing avec vue mer. Parking inclus. Proche plages et centre commercial BAB2.',
    source: 'leboncoin',
    external_url: 'https://leboncoin.fr',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    user_id: 'pro-1',
    type: 'vente',
    title: 'Villa T5 piscine',
    location: 'Biarritz · Côte des Basques',
    price: 895000,
    surface: 165,
    rooms: 5,
    description: 'Magnifique villa T5 avec piscine et jardin de 400m². Vue imprenable sur la Côte des Basques. Prestations haut de gamme.',
    source: 'howner',
    external_url: null,
    is_native: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    user_id: 'pro-2',
    type: 'neuf',
    title: 'Programme Les Allées — 4 lots',
    location: 'Bayonne · Quartier Saint-Esprit',
    price: 195000,
    surface: 55,
    rooms: 2,
    description: 'Programme neuf RT2020. Du T2 au T4. Éligible PTZ. Livraison Q3 2026. Parking en sous-sol inclus.',
    source: 'howner',
    external_url: null,
    is_native: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    user_id: null,
    type: 'location',
    title: 'Maison T4 avec jardin',
    location: 'Boucau · Boucau Haut',
    price: 1350,
    surface: 110,
    rooms: 4,
    description: 'Maison T4 avec jardin clos et garage. Quartier calme, proche écoles et commerces. Disponible immédiatement.',
    source: 'pap',
    external_url: 'https://pap.fr',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    user_id: null,
    type: 'vente',
    title: 'T4 rénové vue Nive',
    location: 'Bayonne · Grand Bayonne',
    price: 320000,
    surface: 85,
    rooms: 4,
    description: 'T4 entièrement rénové avec terrasse et vue sur la Nive. Cuisine équipée, parquet, prestations soignées.',
    source: 'bienici',
    external_url: 'https://bienici.com',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    user_id: null,
    type: 'vente',
    title: 'T2 investisseur centre Bayonne',
    location: 'Bayonne · Centre',
    price: 175000,
    surface: 38,
    rooms: 2,
    description: 'T2 idéal investisseur. Actuellement loué 650€/mois. Rentabilité 4.5%. Copropriété bien entretenue.',
    source: 'seloger',
    external_url: 'https://seloger.com',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    user_id: 'pro-1',
    type: 'vente',
    title: 'Maison architecte T6',
    location: 'Arcangues · Village',
    price: 1250000,
    surface: 220,
    rooms: 6,
    description: 'Maison d\'architecte contemporaine. 6 pièces, 220m², terrain 1200m². Piscine à débordement, vue Pyrénées.',
    source: 'howner',
    external_url: null,
    is_native: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    user_id: null,
    type: 'location',
    title: 'Studio meublé étudiant',
    location: 'Bayonne · Université',
    price: 520,
    surface: 22,
    rooms: 1,
    description: 'Studio meublé proche campus universitaire. Kitchenette équipée, salle d\'eau. Charges comprises.',
    source: 'leboncoin',
    external_url: 'https://leboncoin.fr',
    is_native: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    user_id: 'pro-3',
    type: 'neuf',
    title: 'Résidence Les Terrasses — 12 lots',
    location: 'Anglet · Montbrun',
    price: 285000,
    surface: 65,
    rooms: 3,
    description: 'Programme neuf standing. Du T2 au T4 avec terrasses plein sud. Parking + local vélo. Livraison Q1 2027.',
    source: 'howner',
    external_url: null,
    is_native: true,
    created_at: new Date().toISOString(),
  },
]
